### ISSUE TITLE
Cant use jjb varaiables inside groovy script

### ISSUE THREAD

**Issue by Tstrul-work** [bgaifullin/jenkins-job-builder-active-choice#18]
Hey,
When im trying to use a parameter from jjb i get it as a simple string and not the var content:

```
      - active-choices:
          name: TEST
          description: test
          script:
            groovy: |-
              '{package_name}'
            use-groovy-sandbox: false
```

this is inside a template - package_name is a variable passed for this template
am i doing something wrong or there is no support for such case?
